"""Добавлено поле комментарий в печати

Revision ID: 093bb1c6e0d1
Revises: eefa8fc703bf
Create Date: 2026-01-03 13:36:50.514152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093bb1c6e0d1'
down_revision: Union[str, Sequence[str], None] = 'eefa8fc703bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'printing',
        sa.Column('comment', sa.String(length=500), nullable=True)
    )

    op.execute("UPDATE printing SET comment = '' WHERE comment IS NULL")

    op.alter_column('printing', 'comment', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printing', 'comment')
    # ### end Alembic commands ###
