"""add relation between order and printing cost report

Revision ID: 82e5e756d960
Revises: 8d7848fdde14
Create Date: 2026-01-15 13:22:12.355072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e5e756d960'
down_revision: Union[str, Sequence[str], None] = '8d7848fdde14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'unit_count',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('printing_cost_report', sa.Column('order_cost_report_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'printing_cost_report', 'order_cost_report', ['order_cost_report_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printing_cost_report', type_='foreignkey')
    op.drop_column('printing_cost_report', 'order_cost_report_id')
    op.alter_column('order', 'unit_count',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
