"""Добавлена себестоимость печати

Revision ID: 8d7848fdde14
Revises: 093bb1c6e0d1
Create Date: 2026-01-03 14:45:38.208325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7848fdde14'
down_revision: Union[str, Sequence[str], None] = '093bb1c6e0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку временно nullable
    op.add_column(
        'printing_cost_report',
        sa.Column('edition_cost_price', sa.Numeric(), nullable=True)
    )

    # 2. Заполняем существующие данные
    op.execute("""
        UPDATE printing_cost_report
        SET edition_cost_price = unit_cost_price * (edition_cost / unit_cost)
        WHERE unit_cost IS NOT NULL AND unit_cost != 0
    """)

    # 3. Запрещаем NULL
    op.alter_column(
        'printing_cost_report',
        'edition_cost_price',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printing_cost_report', 'edition_cost_price')
    # ### end Alembic commands ###
