"""empty message

Revision ID: ae46e8b6379c
Revises: 8f45e73c8c37
Create Date: 2026-01-02 17:02:51.305020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae46e8b6379c'
down_revision: Union[str, Sequence[str], None] = '8f45e73c8c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_cost_report',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('cost_report_id_seq')"), nullable=False),
    sa.Column('unit_cost_price', sa.Numeric(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(), nullable=False),
    sa.Column('edition_cost', sa.Numeric(), nullable=False),
    sa.Column('profit_after_tax', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('order_cost_report_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'order', 'order_cost_report', ['order_cost_report_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'order_cost_report_id')
    op.drop_table('order_cost_report')
    # ### end Alembic commands ###
