"""empty message

Revision ID: e0d6cef6ab55
Revises: 92fc9c6b779d
Create Date: 2026-01-01 18:04:38.992209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d6cef6ab55'
down_revision: Union[str, Sequence[str], None] = '92fc9c6b779d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column('order_id', sa.BigInteger(), nullable=True),
        sa.Column('name', sa.String(length=500), nullable=False, comment='Название операции.'),
        sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=False, comment='Стоимость операции в руб.'),
        sa.Column('description', sa.String(length=500), nullable=True, comment='Описание операции'),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order', 'economy_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'economy_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('operation')
    # ### end Alembic commands ###
