"""Добавлено поле для количества сборных изделий в заказе

Revision ID: eefa8fc703bf
Revises: ae46e8b6379c
Create Date: 2026-01-03 13:19:09.892567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefa8fc703bf'
down_revision: Union[str, Sequence[str], None] = 'ae46e8b6379c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('unit_count', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE order SET unit_count = 1 WHERE unit_count IS NULL")

    op.alter_column('order', 'unit_count', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'unit_count')
    # ### end Alembic commands ###
