# Стадия сборки
FROM node:18-alpine AS builder
WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm ci

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

# Копируем остальной код и собираем
COPY . .
RUN npm run build

# Стадия запуска
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html

# Кастомный конфиг nginx (по желанию)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
